#ifndef NAUR_FI_F103_CONFIG_H_INCLUDED
#define NAUR_FI_F103_CONFIG_H_INCLUDED

	#define	NAUR_FI_F103		1
	//	#define	NAUR_FI_F446	0
	#define NAUR_FI_DEBUG_MODE	1

#endif	//	NAUR_FI_F103_CONFIG_H_INCLUDED
